[package]
name = "football_simulator"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "src/core" }
actix-web = "3.3.2"
askama = "0.10.5"
actix-files = "0.5.0"
serde_json = "1.0.62"
serde = "1.0.123"
parking_lot = "0.11.1"
log = { version = "0.4.14", features = ["release_max_level_error"] }
env_logger = "0.8.3"
itertools = "0.10.0"
